.env.example, README.md, core/base.py, core/migrations.py, core/settings.py, mint/migrations.py, pyproject.toml, tests/test_wallet.py, wallet/cashu.py, wallet/crud.py, wallet/migrations.py, wallet/wallet.py
This PR makes the Cashu wallet keep track of the tokens that it reserved for sending so to avoid annoying double spending attempts.
=> Keep track of available tokens

README.md
I believe author intends to use "prepend" not "prepent" on Line 63. Small change, big meaning.
=> Update README.md - Super Minor Typo Fix

README.md, cashu/core/settings.py, cashu/mint/crud.py, cashu/wallet/crud.py, pyproject.toml, setup.py
The default timestamps for keysets are fixed. Before, it was wrongly using the plain SQLite syntax, but now it actually writes the unix timestamp as an int (for SQLite compatibility).
=> default unix timestamp

.env.example, README.md, cashu/core/settings.py, cashu/wallet/cli.py, cashu/wallet/cli_helpers.py, cashu/wallet/crud.py, cashu/wallet/migrations.py, pyproject.toml, setup.py
- Use bech32 nostr keys for all operations (including the config file). 
- Remember when the last nostr DM check took place so we don't have to scan through all past DMs again
- Update [callebtc/python-nostr](https://github.com/callebtc/python-nostr) to 0.7
- Bump version to `0.9.2`
=> Nostr bech32 dm

cashu/wallet/cli/cli.py, cashu/wallet/cli/nostr.py
- easier command for sending `cashu send 10 user@domain.com` without `-n` flag (optional now)
- sleep 5s after sending to make sure websockets have sent out data
- parsing for nip05 identifiers without a user, i.e. `me.com` becomes `_@me.com`
=> nostr: send to nip05

cashu/wallet/wallet.py, tests/test_wallet.py
=> wallet: invalidate proofs without checking with mint

cashu/wallet/cli/cli.py
This might be useful in cases the mint becomes unavailable. See #116.
To remove a pending token from the list use `cashu burn --delete send-id`. 
The token is forcefully deleted without further checking with the mint (i.e. if token is already spent) also in cases where the mint would still be available.
=> Add ability to force-delete pending token by send ID

cashu/wallet/cli/cli.py
When burning specific token via cashu burn "token", there was a TypeError in line 459 of cli.py:
`proofs = [Proof(**p) for p in json.loads(base64.urlsafe_b64decode(token))]`
`
TypeError: cashu.core.base.Proof() argument after ** must be a mapping, not str
`
=> Fix: TypeError in burn token

cashu/wallet/cli/cli_helpers.py
Wallet used to load the mint with the keyset_id it encountered first in the database instead of loading the most recent one which is determined by asking the mint directly because we use `mint_wallet.load_mint(keyset_id=None)` now.
=> fix: load mint with most recent keyset

cashu/core/settings.py, cashu/mint/router.py
See #151.
Adds flag `mint_peg_out_only` in settings. If set and someone tries to mint or requests minting, an error is raised.
=> Allow setting mint as peg-out only

cashu/wallet/cli/cli_helpers.py, cashu/wallet/wallet.py
Wallet loaded keys of the redeemed token (input) instead of the newly issued tokens (outputs). Mint public keys are used in `step3_Alice()`
=> load keys of output, not of inputs

tests/test_crypto.py
The test_step2() doesn't call step2_bob() of the b_dkhe module and therefore is only testing step1_alice()
=> fix: test_step2

cashu/wallet/cli/cli.py
While making myself familiar with some of the available cashu commands, I noticed that `burn` command parameter validation error message contains "oror" instead of "or". (Found my way here through WBD episode #647, the project looks very promising!).
=> fix double "or" typo in burn parameter validation error message

cashu/core/b_dhke.py, cashu/mint/ledger.py, cashu/wallet/wallet.py
* Fix comments (DLEQ sign error)
* Fix alice_verify_dleq in d_dhke.py
* Fix_generate_promise in ledger.py
* Fix verify_proofs_dleq in wallet.py
=> Use C_ instead of C in verify DLEQ!

cashu/wallet/wallet.py
Coinselection that prioritizes spending tokens from old epochs first and then adds tokens from most recent epoch until the target amount is met, starting from the largest ones (smallest anonymity set).
=> [Wallet] coinselection of all tokens from old epochs

cashu/core/base.py, cashu/core/settings.py, cashu/mint/ledger.py, cashu/mint/router.py
Add parameter `mint_max_peg_in` and `mint_max_peg_out` to optionally limit peg in/out for mint. If set, these are added to `/info`.
Issues: closes #196
=> Allow to set maximum peg in/out for mint

.gitignore, cashu/core/settings.py, cashu/mint/startup.py
If the mint's private key is not available, the ledger cannot be created because no pubkey can be derived. We now explicitly assert this with a descriptive error message.
Additionally fixed some typing errors.
Closes #179
=> Assert `mint_private_key` is available at startup

cashu/mint/router.py, tests/test_mint_api.py
the Mint API `/mint?amount=<int>` currently doesn't do any input validation to check that the amount is positive or a possible amount of sats (21 Quadrillion) leading to some errors downstream -- depending on the number, the DB will reject the insert query because the amount is over the maximum `INTEGER` or LNBits/Lightning Node will also reject it.
=> Mint API: Check `?amount` is within a sensible range

cashu/core/db.py, cashu/mint/migrations.py, cashu/wallet/migrations.py
Postgres compatibility: Cast columns of type `INT` to `BIGINT`. Closes #228
=> db: postgres cast int to bigint

Dockerfile
The dockerfile was failing to build because it was missing some dependencies needed by https://github.com/rustyrussell/secp256k1-py
To test:
```
docker build .
```
=> Add secp256k1 deps to dockerfile

cashu/wallet/api/responses.py, cashu/wallet/api/router.py, tests/test_api.py
Define responses of wallet API using pydantic's `BaseModel` and fastapi's `response_model`.
=> [Wallet] Define responses for API

cashu/core/settings.py, cashu/wallet/api/api_server.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, pyproject.toml
=> Allow to start wallet API by cashu --daemon

cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/helpers.py, cashu/wallet/wallet.py, tests/test_cli.py, tests/test_wallet_api.py
Sending tokens that are already available without doing a `/split`. Available in the wallet CLI and API.
=> [Wallet] send without split

cashu/mint/app.py, cashu/wallet/api/app.py, cashu/wallet/api/responses.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/cli/cli_helpers.py, cashu/wallet/helpers.py, cashu/wallet/wallet.py, tests/test_wallet_api.py
Profiling results showed that calling `wallet.load_proofs()`, specifically the list comprehension `[Proof(**dict(r)) for r in rows]` in `wallet/crud.py` spends a lot of CPU time. 
* gets rid of most unnecessary `load_proofs` calls
* skips db load if `wallet.proofs` is already populated in `load_proofs()`
* New argument `load_proofs(reload=True)` forces a db reload
* Removes most `initial_balance` and `balance` in wallet api
* Tests: Add fixture `wallet` to `wallet_api_test`
=> [Wallet] DB optimization for faster payments

.env.example, README.md, cashu/core/base.py, cashu/core/p2pk.py, cashu/core/script.py, cashu/core/settings.py, cashu/mint/ledger.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/helpers.py, cashu/wallet/nostr.py, cashu/wallet/wallet.py, setup.py, tests/conftest.py, tests/test_wallet.py
Pay to Public Key (P2PK) allows the sender to lock tokens to a recipient public key. The lock is enforced by the mint and unlocked using a signature of the intended recipient.
For a normal ecash operation, `Alice` generates a random `secret` that the mint blind-signs. If anyone later presents `secret` and the signature `C` to the mint, the ecash transaction is valid. Naturally, we want to express more complex spending conditions for transactions. That's where P2PK and P2SH spending condition come in. 
To lock tokens to a spending condition, `Alice` needs to generate a special type of `secret`. If the mint encounters a `secret` with a well-known format corresponding to P2PK or P2SH locks, it will demand other conditions to be met in order to validate the transaction. 
The well-known …
=> [Wallet/mint] P2PK with timelocks

cashu/mint/ledger.py
Mitigates a possible race condition. Invalidates proofs while they are still pending.
=> [Mint] Invalidate proofs while pending

cashu/core/errors.py, cashu/mint/app.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/wallet/api/app.py, cashu/wallet/wallet.py, tests/test_mint_api.py, tests/test_wallet.py, tests/test_wallet_p2pk.py
Main changes:
- `app.py`: mint now has a FastApi middleware that catches all exceptions and returns proper HTTP errors with status codes (instead of always returning code 200 with an error JSON)
- `router.py` now just let's the error bubble up to the middleware instead of returning the error
- `errors.py`: Start to define error types with error codes.
- Errors as JSON example: `{"detail":"Keyset not found.","code":12001}`
- `ledger.py`: raise new custom error types.
- `wallet.py`: `raise_on_error` for new error types.
=> Add custom error types

.env.example, .gitignore, Makefile, cashu/wallet/api/router.py, pyproject.toml, tests/conftest.py, tests/test_cli.py, tests/test_mint.py, tests/test_wallet.py, tests/test_wallet_api.py, tests/test_wallet_p2pk.py, tests/test_wallet_p2sh.py
everything works now for me locally.
for description look at my commit messages :)
=> [FEAT] Improve tests

cashu/wallet/api/router.py
Call load_proofs to enable a non-zero balance to be detected in the mint wallet to assess whehter or not the payment can be made.
(cherry picked from commit 0e058fa69f53689c7d9d37f02b4f5a62c58f03e7)
=> load the proofs or we get a zero balance

cashu/core/base.py, cashu/core/p2pk.py, cashu/mint/ledger.py, cashu/mint/main.py, cashu/wallet/p2pk.py, cashu/wallet/protocols.py, cashu/wallet/secrets.py, cashu/wallet/wallet.py, tests/test_wallet_p2pk.py
Refactor P2PK logic into a new subclass `P2PKSecret` and adjust to changes in https://github.com/cashubtc/nuts/pull/40 where now multiple entries per tag are allowed (multiple entries in the `pubkeys` tag)
Todo:
=> Refactor: P2PKSecret

cashu/core/base.py, cashu/core/p2pk.py, cashu/mint/conditions.py, cashu/wallet/api/responses.py, cashu/wallet/crud.py, cashu/wallet/htlc.py, cashu/wallet/p2pk.py, cashu/wallet/wallet.py, tests/test_wallet_htlc.py, tests/test_wallet_p2pk.py
P2PK, P2SH, and HTLC witnesses are now all stored in the same field `Proof.witness`. Further structure inside `Proof.witness` specific to each spending condition type is encoded as JSON.
Closes #340
=> Coalesce all witness fields to `Proof.witness`

cashu/wallet/wallet.py
Solves issue in #286 by joining mint URL and endpoint safely with `urllib.parse.urljoin`.
=> Join mint URL and endpoint in a safe way

cashu/mint/ledger.py, tests/test_wallet.py
fees were not returned if the fees were zero
=> [Wallet] Fix fee return for fee=0

.gitmodules, README.md, cashu/nostr/.gitignore, cashu/nostr/bech32.py, cashu/nostr/client/cbc.py, cashu/nostr/client/client.py, cashu/nostr/delegation.py, cashu/nostr/event.py, cashu/nostr/filter.py, cashu/nostr/key.py, cashu/nostr/message_pool.py, cashu/nostr/message_type.py, cashu/nostr/pow.py, cashu/nostr/relay.py, cashu/nostr/relay_manager.py, cashu/nostr/subscription.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/nostr.py
=> [Wallet] Add nostr dependency directly to repo

.pre-commit-config.yaml, cashu/mint/ledger.py, cashu/mint/verification.py, cashu/wallet/wallet.py
Compatibility issues with older version of cashu-ts
=> Mint: Allow 0-valued amounts for blank outputs

cashu/core/base.py, cashu/core/htlc.py, cashu/core/p2pk.py, cashu/core/secret.py, cashu/mint/conditions.py, cashu/wallet/htlc.py, cashu/wallet/p2pk.py, tests/test_wallet_htlc.py
More rigid structure in validation and full documentation of all steps for P2PK input and output checking, and for HTLC input checking.
=> Refactor secret conditions

cashu/lightning/fake.py, cashu/lightning/lnbits.py
LNbits backend now responds with correct pydantic basemodels, instead of namedtuples before.
=> Fix LNbits backend to use proper BaseModels

cashu/wallet/wallet.py
Implements a decorator for mint API functions that require the mint to be loaded. The decorator makes sure that keys are loaded and if not, loads them.
=> Wallet: ensure that mint keys are loaded before calling appropriate api methods

.env.example, .github/workflows/ci.yml, .github/workflows/regtest.yml, cashu/core/settings.py, cashu/lightning/__init__.py, cashu/lightning/corelightningrest.py, cashu/lightning/lndrest.py, cashu/lightning/macaroon.py, cashu/mint/crud.py
Adds CoreLightning REST interface and enables regtests
=> add CoreLightningRestWallet

.github/workflows/ci.yml, cashu/core/base.py, cashu/core/db.py, cashu/core/errors.py, cashu/core/logging.py, cashu/mint/crud.py, cashu/mint/ledger.py, cashu/mint/migrations.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/mint/startup.py, tests/test_mint_db.py, tests/test_mint_keysets.py
=> Keysets per seed and postgres

cashu/core/base.py, cashu/core/crypto/aes.py, cashu/core/settings.py, cashu/mint/crud.py, cashu/mint/decrypt.py, cashu/mint/ledger.py, cashu/mint/migrations.py, cashu/mint/startup.py, tests/conftest.py, tests/test_mint_init.py, tests/test_mint_keysets.py
=> mint: add seed decrypt

.github/workflows/ci.yml, tests/conftest.py
For safety, so we don't accidentally wipe any production db with the tests.
=> Mint: check that test db is different from main db

cashu/core/base.py, cashu/lightning/fake.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/wallet/wallet.py, tests/test_mint_api.py
@ngutech21 we're now returning the expiry, in case it is not present or doesn't apply, it returns `0`. We should probably defined that in the NUT.
=> Mint: add expiry to quotes, closes #385

cashu/mint/router.py
According to the current spec the nut4 info-response provided by nutshell is missing the disabled-flag
https://github.com/cashubtc/nuts/blob/main/04.md
BTW nutshell is providing a disabled flag for nut5, which is not part of the spec. This is not a problem for a client, because additional information in the json is ignored, but I think this is an error in the spec. The mint runner should have the option to disable minting and melting.
=> add missing disabled-flag to nut4

.github/workflows/checks.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, Makefile, cashu/core/crypto/b_dhke.py, cashu/lightning/blink.py, poetry.lock, pyproject.toml, tests/test_crypto.py
=> Revert "Dev: Update ruff precommit hooks"

cashu/core/settings.py, cashu/wallet/cli/cli.py, cashu/wallet/nostr.py
Main thread used to exit too early but nostr threads kept running. Now the main thread will wait for a key press to exit.
=> Wallet: fix nostr receive

README.md
This pull request adds a step to checkout the latest tag in the `cashu` repository before installing the dependencies. This ensures that the latest stable version of the code is used for the installation process.
=> Add checkout latest tag

cashu/core/base.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/wallet/wallet.py, cashu/wallet/wallet_deprecated.py
This pull request updates the PostRestoreResponse class in order to use the "signatures" attribute instead of the deprecated "promises" attribute. This change ensures backwards compatibility with old clients and improves code clarity.
Implement change in https://github.com/cashubtc/nuts/pull/87
=> Update PostRestoreResponse class to use "signatures" instead of "promises"

cashu/core/base.py, cashu/mint/crud.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/mint/verification.py, cashu/wallet/wallet.py, tests/test_mint_api.py, tests/test_mint_operations.py
This PR fixes the check_proofs_state method in the Ledger class. It updates the method to use the Y attribute of the Proof objects instead of the secret attribute. This change ensures that the method works correctly with the updated ProofState model.
Implements change in NUT-07: https://github.com/cashubtc/nuts/pull/93
=> Token state check with Y

cashu/mint/ledger.py
Combination of Blink and eNuts revealed a but where internal payments would not be detected as such because eNuts requests payment of an upper-case LN invoice and the corresponding internal mint request string is a lower-case bolt11 invoice.
=> Melt quotes use case-insensitive request

cashu/core/base.py, cashu/mint/router.py, tests/test_mint_api.py
Addresses https://github.com/cashubtc/nuts/pull/82
Closes https://github.com/cashubtc/nutshell/issues/485
=> NUTs: info endpoint method settings

.env.example, .github/workflows/tests.yml, Makefile, README.md, cashu/core/settings.py, cashu/lightning/__init__.py, cashu/lightning/base.py, cashu/lightning/blink.py, cashu/lightning/corelightningrest.py, cashu/lightning/fake.py, cashu/lightning/lnbits.py, cashu/lightning/lndrest.py, cashu/lightning/strike.py, cashu/mint/ledger.py, cashu/mint/startup.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/cli/cli_helpers.py, cashu/wallet/helpers.py, docker-compose.yaml, tests/helpers.py
- Add 'usd' support for `FakeWallet`
- Fix: After a `receive`, print balance in the unit of the received token in Wallet CLI, not in the default wallet unit.
=> Mint: Fakewallet support for USD

.env.example, cashu/core/settings.py, cashu/mint/app.py, cashu/mint/limit.py, cashu/mint/middleware.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, poetry.lock, pyproject.toml
This pull request adds the slowapi library to the project. The slowapi library is used for rate limiting requests to the mint API.
=> Mint: Add slowapi

tests/test_crypto.py
Implements https://github.com/cashubtc/nuts/pull/105
=> Add test vector for NUT-12

cashu/mint/conditions.py, cashu/wallet/cli/cli.py, cashu/wallet/crud.py, cashu/wallet/migrations.py, cashu/wallet/p2pk.py, cashu/wallet/wallet.py, tests/test_mint_lightning_blink.py, tests/test_wallet_cli.py, tests/test_wallet_p2pk.py
- Updates deprecated `datetime.utcfromtimestamp` in the `cashu/wallet/cli/cli.py` file;
- Adds new options to the `invoices` CLI command:
- `--only-paid` (`-op`): retrieve only paid invoices;
- `--only-unpaid` (`-ou`): retrieve only unpaid invoices;
- `--pending` (`-p`): retrieve only pending invoices.
Pending invoice was defined as invoices with `paid = False` and `out = False` (not sure if this is right).
Closes #313 .
=> Issue #313: allow checking pending invoices

cashu/wallet/wallet_deprecated.py
Fixes a bug introduced in #507 when using the deprecated API.
=> [Wallet] Fix regression bug for mint request

cashu/core/settings.py
The default setting was `[""]` which caused a startup failure.
=> [Mint] default setting for `mint_derivation_path_list`

cashu/mint/startup.py
I think the blink key is missing here:
for key, value in settings.dict().items():
if key in [
"mint_private_key",
"mint_seed_decryption_key",
"nostr_private_key",
"mint_lnbits_key",
"mint_strike_key",
=> Add blink key to startup

cashu/mint/ledger.py, cashu/mint/router.py, cashu/wallet/cli/cli.py
Remove option to skip checking payment state in `get_melt_quote` and always check it if unpaid.
Todo: check if the melt routine assumed that it would skip the check in order to avoid double-checking. If so, remove duplicate check in melt routine.
=> Mint: refactor melt quote

.github/workflows/regtest.yml, cashu/core/base.py, cashu/core/settings.py, cashu/lightning/base.py, cashu/lightning/blink.py, cashu/lightning/corelightningrest.py, cashu/lightning/fake.py, cashu/lightning/lnbits.py, cashu/lightning/lndrest.py, cashu/lightning/strike.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/lightning/lightning.py, cashu/wallet/mint_info.py, cashu/wallet/wallet.py, cashu/wallet/wallet_deprecated.py, tests/conftest.py, tests/test_mint_init.py, tests/test_mint_lightning_blink.py, tests/test_mint_operations.py, tests/test_mint_regtest.py, tests/test_wallet.py, tests/test_wallet_regtest.py, tests/test_wallet_regtest_mpp.py
Todo:
Implements https://github.com/cashubtc/nuts/pull/103
=> Multinut LND

cashu/mint/verification.py, cashu/wallet/transactions.py
The pull request updates the fee calculation in two places to use integer division instead of `math.ceil()`. This change ensures that the fees are rounded up to the nearest whole number. The previous implementation used `math.ceil()` which rounded up to the nearest integer, but we want to round up to the nearest whole number. This change improves the accuracy of the fee calculation.
=> Use integer division for fee calculation

cashu/core/base.py, cashu/core/models.py, cashu/mint/crud.py, cashu/mint/db/read.py, cashu/mint/db/write.py, cashu/mint/events/events.py, cashu/mint/ledger.py, cashu/mint/migrations.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/mint/tasks.py, cashu/wallet/cli/cli.py, cashu/wallet/lightning/lightning.py, cashu/wallet/migrations.py, cashu/wallet/subscriptions.py, cashu/wallet/v1_api.py, cashu/wallet/wallet.py, cashu/wallet/wallet_deprecated.py, tests/conftest.py, tests/test_mint_api.py, tests/test_mint_init.py, tests/test_mint_lightning_blink.py, tests/test_mint_regtest.py, tests/test_wallet_p2pk.py, tests/test_wallet_regtest.py, tests/test_wallet_subscription.py
This pull request adds a new `state` field to the quotes in the code. It also fixes failing tests related to the `SpentState` enum, which has been renamed to `ProofSpentState`.
Implements https://github.com/cashubtc/nuts/pull/141 and https://github.com/cashubtc/nuts/pull/136
=> NUT-04 and NUT-05: Add `state` field to quotes

.env.example, cashu/core/base.py, cashu/core/settings.py, cashu/lightning/__init__.py, cashu/lightning/fake.py, cashu/lightning/strike.py, cashu/mint/startup.py, cashu/mint/tasks.py, cashu/wallet/cli/cli.py
This pull request adds support for EUR in the Strike backend. Previously, only USD was supported. With this change, users will be able to use Strike for BTC, USD, and EUR.
- Configuration in `.env` changes from `StrikeUSDWallet` to `StrikeWallet`
- `FakeWallet` now supports EUR as well
- Invoice listener only for backends that support incoming payment streams
- Invoice listener now restarts on error
=> [Mint] Add support for BTC and EUR in `StrikeWallet` backend, add EUR to `FakeWallet`

.env.example, cashu/core/settings.py, cashu/lightning/lndrest.py
- Add MINT_LND_REST_CERT_VERIFY bool variable that when set to False allows verify=False for httpx and ignore LND selfsigned certificate validation
On branch main
Your branch is up to date with 'origin/main'.
Changes to be committed:
modified:   .env.example
modified:   cashu/core/settings.py
modified:   cashu/lightning/lndrest.py
=>  add MINT_LND_REST_CERT_VERIFY env bool that when set to False allow to skip certificate validation for LND api call

cashu/wallet/cli/cli.py, cashu/wallet/cli/cli_helpers.py, cashu/wallet/proofs.py
The wallet not properly supports receiving back all pending tokens from multiple mints and multiple units.
=> Fix `receive -a` to receive all pending tokens

cashu/core/base.py, cashu/core/settings.py, cashu/wallet/wallet.py, tests/test_mint_fees.py
This pull request fixes the loading of b64 keysets in the Mint module and adds a new option to set b64 keysets as inactive in the WalletSettings module. The changes ensure backwards compatibility with old keysets and allow the wallet to only use new keyset versions.
=> Fix loading b64 keysets and add option to set b64 inactive in WalletSettings

cashu/core/models.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/mint/router_deprecated.py, cashu/wallet/api/router.py, cashu/wallet/cli/cli.py, cashu/wallet/helpers.py, cashu/wallet/lightning/lightning.py, cashu/wallet/nostr.py, cashu/wallet/proofs.py, cashu/wallet/secrets.py, cashu/wallet/transactions.py, cashu/wallet/v1_api.py, cashu/wallet/wallet.py, cashu/wallet/wallet_deprecated.py, tests/test_mint_api.py, tests/test_mint_fees.py, tests/test_mint_init.py, tests/test_mint_operations.py, tests/test_mint_regtest.py, tests/test_wallet.py, tests/test_wallet_htlc.py, tests/test_wallet_p2pk.py, tests/test_wallet_regtest.py, tests/test_wallet_restore.py, tests/test_wallet_subscription.py
- Rename `split_to_send` to `swap_to_send` 
- Add new `--force-swap` flag to `cashu send` command
- `_select_proofs_to_swap` coin selection now spends *all* proofs form inactive keysets first
=> Wallet: add CLI flag `--force-swap` flag and force swapping all inactive keysets

CONTRIBUTING.md
This pull request adds instructions for the .env file in the project's README.md. It provides information on how to set up the environment and configure the backend for the Nutshell application. Additionally, it includes details on formatting, using the FakeWallet backend for tests, running tests in the Lightning regtest environment, and enabling profiling and V0 API support.
=> `CONTRIBUTING.md`: Add instructions for .env file

cashu/wallet/helpers.py
let me know if you disagree but changed cli wallet to by default generate P2PK locks with sigflag `SIG_INPUTS` instead of `SIG_ALL`
=> Wallet: default to `SIG_INPUTS` in P2PK lock

cashu/core/models.py, cashu/core/settings.py, cashu/mint/router.py
This pull request fixes an issue where the contact field in the wallet was not being parsed correctly if it was in the old format. The issue was identified in commit "wallet parse contact field if its old format". The problem has been resolved by adding a root validator to preprocess the deprecated contact field and convert it to the new format. This ensures that the contact field is parsed correctly in all cases.
=> Fix parsing of old format contact field in wallet

cashu/mint/db/read.py, cashu/mint/db/write.py, cashu/mint/ledger.py, cashu/mint/verification.py, tests/test_db.py, tests/test_mint_db.py, tests/test_wallet.py
checks relative to proof spendable that access the DB are now performed inside the lock of `_set_proofs_pending`.
Now `test_split_race_condition` passes.
=> Fix race condition

cashu/wallet/utils.py, cashu/wallet/wallet.py, tests/test_wallet_utils.py
This pull request adds a new function `sanitize_url` that sanitizes the provided URL by extracting the host, lowercasing it, and removing any trailing slashes. The function is then used to sanitize the mint URL before adding it to the wallet. This ensures that the mint URL is in the correct format and avoids any potential issues caused by inconsistent URL formatting.
Closes #603
=> Sanitize mint URL before adding

cashu/core/models.py, cashu/lightning/base.py, cashu/lightning/blink.py, cashu/lightning/clnrest.py, cashu/lightning/corelightningrest.py, cashu/lightning/fake.py, cashu/lightning/lnbits.py, cashu/lightning/lnd_grpc/lnd_grpc.py, cashu/lightning/lndrest.py, cashu/lightning/strike.py, cashu/mint/ledger.py, cashu/wallet/cli/cli.py, cashu/wallet/lightning/lightning.py, cashu/wallet/v1_api.py, cashu/wallet/wallet.py, mypy.ini, tests/test_mint.py, tests/test_wallet_cli.py, tests/test_wallet_lightning.py
Implements https://github.com/cashubtc/nuts/pull/144/
=> NUT-04: add description

cashu/core/models.py, cashu/mint/features.py, tests/test_mint_api.py
ISTM that https://github.com/cashubtc/nutshell/pull/613 implements description for mint operations, but this feature is not properly announced via NUT-06
This PR does two things in order to implement it:
+ untangle MintMeltMethodSetting into MintMethodSetting and MeltMethodSetting
+ add description to MintMethodSetting
Please pay extra attention to rewrite of function `LedgerFeatures`.
Also I am not really sure how to test it properly, but at least I tried that `curl http://127.0.0.1:3338/v1/info` now returns:
``` json
"nuts":{"4":{"methods":[{"method":"bolt11","unit":"sat","description":true}],"disabled":false}
```
instead of (before the PR):
``` json
"nuts":{"4":{"methods":[{"method":"bolt11","unit":"sat"}],"disabled":false}
```
=> feat: announce description in MintMethodSetting

cashu/lightning/lnbits.py, cashu/wallet/cli/cli.py, cashu/wallet/nostr.py, cashu/wallet/transactions.py, cashu/wallet/wallet.py, tests/test_mint_fees.py, tests/test_wallet.py
For keysets with fees, in cases where a melt requires a swap, the wallet did not include the ecash fees in the outputs generated by that swap.
=> Fix: wallet include fees in swap outputs for inputs of successive melt

cashu/core/settings.py, cashu/mint/crud.py, cashu/mint/ledger.py, cashu/mint/migrations.py, cashu/wallet/wallet.py
wallet: turn on flag for deprecate base64 keysets by default
wallet: fix `no_name` wallet that started receiving proofs (Fixes #615)
ledger: fix issue with existing `paid` flag in mint and melt quotes
ledger: method to disable base64 keysets with a flag (default False)
=> Fix: ledger requires deprecated `paid` flags in db + wallet disable base64 keysets by default

cashu/core/base.py, cashu/core/db.py, cashu/core/migrations.py, cashu/mint/crud.py, cashu/wallet/crud.py, poetry.lock, pyproject.toml
A lot of warnings for basically the same thing: use `_mapping` for dictionary interface to `Row`.
=> Bump  SQLAlchemy to 2.0

cashu/core/settings.py, cashu/lightning/fake.py, cashu/mint/ledger.py, tests/test_mint_melt.py
If `get_payment_state` is not able to confirm the `FAILED` state of `pay_invoice`, we know that there must be an issue with either our implementation, the network, or the Lightning backend. We disable all future melts to prevent more stuck payments. Manual intervention is required.
=> Halt melt on exception

cashu/wallet/cli/cli.py, cashu/wallet/v1_api.py, cashu/wallet/wallet.py, tests/test_mint_operations.py, tests/test_wallet.py, tests/test_wallet_cli.py
This pull request introduces a new API endpoint to retrieve mint and melt quotes from the wallet. The `get_mint_quote` and `get_melt_quote` methods have been added to fetch existing quotes based on their IDs. Additionally, the minting process now checks the state of the mint quote before proceeding, ensuring that actions are only taken when the quote is valid. Tests have been updated to verify the functionality of the new API and its integration with existing processes.
=> Add get quote API to wallet + check proof states in batches

tests/conftest.py
Previously we had a simple `time.sleep(1)` call after `server.start()` which was present to give the Mint's HTTP server time to spin up during test runs. This meant that if the server took longer than 1s to start on a dev's machine for any reason (even intermittently) then tests would fail due to connection errors.
The fix is to use a simple repeated polling check which allows the test runner to start only once the server is confirmed listening.
Drive-by: remove an unnecessary duplicate `settings.mint_host` assignment to the 'all interfaces' IP `0.0.0.0`.
=> wait for uvicorn server to bind before running tests

cashu/core/base.py, cashu/core/htlc.py, cashu/core/p2pk.py, cashu/mint/conditions.py, cashu/mint/db/write.py, cashu/wallet/htlc.py, cashu/wallet/p2pk.py, cashu/wallet/wallet.py, tests/test_wallet_htlc.py, tests/test_wallet_p2pk.py
- Refactor: HTLC signature check now uses the same code as P2PK.
- `HTLCWitness` accepts an array of `signatures`, like `P2PKWitness` does
=> Refactor conditions and fix HTLC multisig

cashu/lightning/fake.py, cashu/mint/ledger.py, cashu/mint/router_deprecated.py, tests/conftest.py, tests/test_mint_api.py, tests/test_mint_api_deprecated.py, tests/test_mint_init.py, tests/test_mint_melt.py
- Enables FakeWallet USD keyset for tests
- Settles mint quote and melt quotes with different units from the same mit via Lightning (in tests via FakeWallet)
=> Mint: settle mint-melt on same mint with different units externally

cashu/wallet/wallet.py
`split_wallet_state` method is returning an unsorted split. Sorting it so that blinded messages in mint request are sorted.
=> sort split from split_wallet_state

cashu/wallet/cli/cli.py, cashu/wallet/helpers.py
Check the payment hash after a melt.
Print a ominous message if the preimage is invalid.
=> Wallet check payment hash

.env.example, cashu/core/models.py, cashu/core/settings.py, cashu/mint/router.py
implements https://github.com/cashubtc/nuts/pull/175 for nutshell
do not merge before https://github.com/cashubtc/nuts/pull/175 is merged
CI failures are unrelated - some poetry in github issues
=> NUT-06: add urls field

cashu/lightning/fake.py
LDK verifies this feature is set as supported on invoices.
=> Add FakeWallet invoice features tag for supported payment secret

cashu/mint/features.py, cashu/wallet/mint_info.py
Introduce a methods key in the info endpoint to enhance the structure of the data returned, aligning with recent updates in the repository.
https://github.com/cashubtc/nuts/pull/190
=> Add MPP methods key to info endpoint

docker/docker-compose.yml
Add a restart policy to ensure the Redis Docker container restarts automatically.
=> Add restart policy for Redis Docker container

.env.example, .github/workflows/regtest.yml
* first two commits are straightforward, they just remove MINT_LND_ENABLE_MPP=True in `.env.example` and `.github/workflows/regtest.yml` since this is default since PR [#667](https://github.com/cashubtc/nutshell/pull/667/commits/457ac30823b3a2f6d2cd448156b8a0fcd0f41867)
* the third commit removes `MINT_CLNREST_ENABLE_MPP: false` from `.github/workflows/regtest.yml` because we probably want to test the default behaviour (which is also True since PR [#667](https://github.com/cashubtc/nutshell/pull/667/commits/457ac30823b3a2f6d2cd448156b8a0fcd0f41867))
Or is there any particular reason why want to keep MPP disabled for CLN in the CI?
=> config cleanup regarding MPP

cashu/core/base.py, cashu/mint/crud.py, cashu/mint/db/write.py, cashu/mint/ledger.py, cashu/mint/migrations.py, cashu/wallet/transactions.py, tests/test_mint_init.py, tests/test_mint_melt.py
Nutshell used to "eat up" overpaid fees in cases where the connection to the Lightning backend might have failed during an ongoing payment. 
Now, the `outputs` provided with a melt operation are stored in the db and the `change` is issued on the melt quote if the startup task detects that a melt quote has been paid while the mint had no connection to the Lightning backend.
=> Issue NUT-08 overpaid Lightning fees for melt quote checks on startup

cashu/mint/cache.py
Ensure Redis connection is only closed if it was successfully initialized and used.
=> Fix Redis teardown logic based on usage

cashu/core/errors.py, cashu/mint/ledger.py, cashu/mint/verification.py
Fixing some error codes that didn't conform to spec.
First reported in #655
=> [FIX] Specs conformant  error codes

cashu/mint/ledger.py, tests/test_wallet_regtest_mpp.py
Reject melt quote requests with invoice strings that reference an internal mint quote.
When the Mint receives these requests, it means some wallet is trying to pay a mint quote for this very Mint with a multi-part payment, which is not possible.
=> [FIX] Reject Internal MPP Melt Quote Requests

cashu/core/base.py, cashu/wallet/cli/cli.py, cashu/wallet/wallet.py
This PR does two things:
* Adds a `cashu decode [OPTIONS] [TOKEN]` command that decodes a token without receiving it and prints it in JSON format.
* In `cashu/wallet/wallet.py:403-405` moves the calls for loading and activating the keyset into the try block so
they don't crash the wallet when the Mint is unreachable.
Related Issue: https://github.com/cashubtc/nutshell/issues/700
=> Add CLI Decode Command

cashu/lightning/clnrest.py, cashu/lightning/lnd_grpc/lnd_grpc.py, cashu/lightning/lndrest.py, cashu/mint/ledger.py, cashu/wallet/cli/cli.py, cashu/wallet/v1_api.py, cashu/wallet/wallet.py, tests/test_wallet_regtest_mpp.py
Follows [this](https://github.com/cashubtc/nuts/pull/220) spec change and fixes some erroneous behaviour in `get_payment_quote`
=> [FIX] NUT-15 mpp amount in millisats

cashu/core/errors.py, cashu/mint/ledger.py, tests/test_mint_melt.py
Introduce a new exception class for handling failed Lightning payments, improving error management in the payment process.
Todo:
=> Add LightningPaymentFailedError exception

cashu/lightning/lnd_grpc/lnd_grpc.py, cashu/lightning/lndrest.py
Tries multiple routes before calling it a day.
=> [NUT-15] LND: Try Multiple Routes

requirements.txt
This upgrades `coincurve` to [v21.0.0](https://github.com/ofek/coincurve/releases/tag/v21.0.0) which brings performance improvements and removes all runtime dependencies!
=> Upgrade `coincurve` to version 21.0.0

cashu/core/models.py, cashu/mint/ledger.py, cashu/mint/router.py, cashu/wallet/v1_api.py, cashu/wallet/wallet_deprecated.py, tests/test_mint_api.py
Implements mandatory changes in https://github.com/cashubtc/nuts/pull/235
=> NUT-04/05: add `amount`, `unit`, `request` to melt and mint quote responses

cashu/mint/migrations.py
Update old proofs and promises to include keyset IDs where they were previously missing, ensuring balance views accurately reflect the state of each keyset.
=> Fix mint migrations: Fill in missing keyset IDs in proofs and promises

cashu/core/mint_info.py, cashu/core/models.py, cashu/core/settings.py, cashu/mint/features.py, cashu/mint/router.py, cashu/wallet/mint_info.py
Introduce a new field for the terms of service URL in the MintInformation class and update the mint_info method to include this URL.
Implements https://github.com/cashubtc/nuts/pull/205
=> Add terms of service URL to MintInformation class

cashu/core/base.py, cashu/mint/crud.py, cashu/mint/keysets.py, cashu/mint/ledger.py, cashu/mint/protocols.py, tests/test_mint_keysets.py
Adds support for keyset rotation while the Mint is still running.
* Tidying up `ledger.py`: moved all mint keyset logic into `LedgerKeysets` in the new file `cashu/mint/keysets.py`  
* Added `maybe_update_derivation_path` which replaces `self.derivation_path` with the the most recent one, if it can find any. (e.g. self.derivation_path = "m'/0'/0'/0'" finds -> "m'/0'/0'/1'). This function is called on startup, preventing the Mint from re-activating an older derivation.
* Added `rotate_next_keyset`. This function:
1. finds the highest counter keyset for `unit`.
2. creates a new derivation path from the old one, increasing the counter by one.
3. creates a new active keyset for the new derivation path.
4. de-activates the old keyset.
5. stores the new keyset to DB.
=> Mint Keyset Rotation

cashu/wallet/migrations.py
we accidentally reused migration 13 for adding the privkey column before: https://github.com/cashubtc/nutshell/blob/b67ffd8705565fb2c2ee4464c39faa1e57344ae7/cashu/wallet/migrations.py#L290
we fix the migration number to 14 now. need to check if it already ran by checking if the column exists
=> Wallet: fix db migration 13 duplicate

cashu/core/settings.py, cashu/wallet/cli/cli.py, cashu/wallet/v1_api.py, cashu/wallet/wallet_deprecated.py, tests/wallet/test_wallet_cli.py
Fixes #711 
Changes:
- Added `--verbose`/`-v` flag to CLI commands
- Added `wallet_verbose_requests` setting to track user preference
- Modified request methods to log when verbose is enabled
- Updated both modern and deprecated API request handlers
Usage:
Run any Nutshell command with the `-v` flag to see all mint communication:
The output will include:
- HTTP method (GET/POST)
- URL path
- Request payload (when applicable)
- Response status code
- Response data
This helps with debugging, learning the protocol, and developing integrations.
=> Add verbose request logging feature to wallet

cashu/mint/conditions.py, cashu/mint/ledger.py
Return `true` in a `SIG_ALL` check if no inputs contain `SIG_ALL` sigflags. 
This prevents an [early P2PK check in `melt`](https://github.com/cashubtc/nutshell/blob/29571287b31224c2a19fd690060c40b912fbc564/cashu/mint/ledger.py#L883) from wrongfully rejecting P2PK locked secrets that only have `SIG_INPUTS` sigflags.
=> [BUGFIX] `SIG_ALL` check returns true for other sigflags

cashu/core/models.py, cashu/mint/features.py, tests/mint/test_mint_api.py
fix nutshell to adhere to the NUT-04 `settings` object
before:
after:
=> add description to NUT-04 method options
