cashubtc/nutshell

- core/b_dhke.py
- core/base.py
- core/secp.py
- mint/app.py
- mint/crud.py
- mint/ledger.py
- mint/migrations.py
- poetry.lock
- pyproject.toml
- wallet/crud.py
- wallet/migrations.py
- wallet/wallet.py
> transition to libsecp256k1

- .env.example
- README.md
- core/base.py
- core/settings.py
- lightning/lnbits.py
- mint/app.py
- mint/ledger.py
- poetry.lock
- pyproject.toml
- setup.py
- wallet/cashu.py
- wallet/crud.py
- wallet/migrations.py
- wallet/wallet.py
New command: `cashu pending`
New .env variable: `CASHU_DIR`
Secrets now base64-encoded.
> Show pending tokens

- cashu/core/base.py
- cashu/core/settings.py
- cashu/mint/app.py
- cashu/mint/ledger.py
- cashu/mint/router.py
- cashu/wallet/cli.py
- cashu/wallet/crud.py
- cashu/wallet/wallet.py
- pyproject.toml
- setup.py
- tests/test_wallet.py
* Pay to secret (client-side)
* Wallet does not request mint keys for balance check.
* Wallet needs to run `load_mint()` upon initialization to fetch keys from mint.
> pay to secret

- cashu/core/settings.py
- pyproject.toml
- setup.py
mint checks lightning invoice amount explicitly
> bump version

- README.md
- cashu/core/settings.py
- cashu/wallet/cli.py
- pyproject.toml
- setup.py
- tests/test_crypto.py
Forces Tor use if not manually disabled.
> Tor or bust

- .github/workflows/tests.yml
- README.md
- cashu/core/settings.py
- cashu/mint/crud.py
- cashu/mint/ledger.py
- cashu/mint/migrations.py
- pyproject.toml
- setup.py
- tests/test_wallet.py
> check pending proofs

- cashu/mint/ledger.py
- cashu/mint/router.py
- tests/test_wallet.py
Refactored changes in PR #70  for the mint.
> Mint: endpoint get pubkeys for keyset

- cashu/wallet/cli.py
Get rid of commands `cashu nsend` and `cashu nreceive`. Replace with:
```
cashu send <amount> -n <nostr_pubkey>
```
and 
```
cashu receive --nostr
```
> remove nsend and nreceive, use send and receive

- README.md
- cashu/core/settings.py
- pyproject.toml
- setup.py
> bump version to 0.7.1.

- cashu/mint/ledger.py
- cashu/wallet/wallet.py
- tests/test_wallet.py
> wallet: mint specific amounts

- cashu/mint/ledger.py
- cashu/mint/router.py
- cashu/wallet/cli/cli_helpers.py
- cashu/wallet/wallet.py
- tests/test_wallet.py
> wallet: load keys without keysets

- .env.example
- cashu/core/settings.py
- cashu/lightning/lnbits.py
- cashu/mint/startup.py
> Mint database setting

- .env.example
- cashu/core/settings.py
- cashu/lightning/__init__.py
- cashu/lightning/fake.py
- cashu/lightning/lnbits.py
- cashu/mint/startup.py
- mypy.ini
> lightning: add fakewallet

- cashu/wallet/cli/cli.py
See #116.
`cashu pending -n 10 --offset 50` will show 10 pending tokens starting from index 50.
> Add ability to show n pending tokens starting from offset

- cashu/wallet/cli/cli.py
Adds the ability to receive all pending tokens at once by `cashu receive -a` . See #116.
> Allow to receive all pending tokens at once

- cashu/core/b_dhke.py
- cashu/lightning/lnbits.py
- cashu/mint/ledger.py
- cashu/wallet/cli/cli.py
- `b_dhke.py` type annotations
- remove legacy code from `ledger.py`
> Type annotations for bdhke

- .env.example
- .github/workflows/tests.yml
- cashu/core/crypto.py
- cashu/core/helpers.py
- cashu/core/settings.py
- cashu/lightning/lnbits.py
- cashu/mint/app.py
- cashu/mint/ledger.py
- cashu/mint/main.py
- cashu/mint/startup.py
- cashu/wallet/__init__.py
- cashu/wallet/cli/cli.py
- cashu/wallet/cli/cli_helpers.py
- cashu/wallet/cli/nostr.py
- cashu/wallet/wallet.py
- tests/test_cli.py
- tests/test_mint.py
- tests/test_wallet.py
Big refactor to use a dynamic settings class.
Config change: `MINT_SERVER_HOST`, `MINT_SERVER_PORT` = `MINT_LISTEN_HOST`, `MINT_LISTEN_PORT`.
> use settings module

- Makefile
- cashu/wallet/cli/cli.py
Switched account. Addressed formatting issue.
> CLI: error handling invalid nostr client key

- Dockerfile
- cashu/core/db.py
Here is a new pull request with the Postgres addition with a change to the Docker file so that it builds. I deleted the other pull request, please use this one.
> Postgres with Dockerfile changes

- cashu/wallet/cli/cli_helpers.py
- cashu/wallet/wallet.py
See #117.
Mints are now sorted by URL. Default for mint selection when spending is mint with largest balance available.
> Fix: Mints are sorted by balance which can suddenly change

- .env.example
- README.md
- cashu/core/base.py
- cashu/core/crypto.py
- cashu/core/settings.py
- cashu/mint/ledger.py
- cashu/mint/router.py
- pyproject.toml
- setup.py
Implements [NUT-09](https://github.com/cashubtc/nuts/pull/10/)
> nut-09 mint info

- cashu/lightning/fake.py
- cashu/mint/ledger.py
- cashu/mint/startup.py
- Removes the need to recompute all keys from old keysets when a new keyset is generated.
- Adds `BRR` settings to `FakeWallet` to create money out of thin air.
Todo: Remove automatic rotation
> [Mint] Fix key rotation

- cashu/mint/ledger.py
Just simple rewording of some debug logs.
> [Mint] Improve logging for keyests

- cashu/core/settings.py
- cashu/mint/startup.py
- tests/conftest.py
> settings: add mint derivation path

- tests/test_tor.py
Tor tests seem to work on Github.
> [Wallet] enable tor tests in CI

- .env.example
- cashu/core/base.py
- cashu/core/settings.py
- tests/conftest.py
- tests/test_mint.py
- tests/test_mint_api.py
- Add REST API tests for mint
- Fix NUT-09 contact info
> [Mint] add mint api tests

- cashu/wallet/cli/cli.py
- cashu/wallet/cli/cli_helpers.py
- cashu/wallet/nostr.py
- cashu/wallet/wallet.py
> [Wallet] Bugfix/enable-funding-multiple-mints

- cashu/core/settings.py
- cashu/mint/app.py
- cashu/mint/ledger.py
- cashu/mint/router.py
New setting: `LOG_LEVEL` can be `INFO, DEBUG, TRACE`.
Trying to find the cause of #195
> [Mint] add trace logs

- cashu/core/db.py
- cashu/mint/ledger.py
> Chore: make format

- cashu/core/db.py
- cashu/core/migrations.py
- cashu/mint/crud.py
- cashu/mint/ledger.py
- cashu/mint/migrations.py
remove changes to Compat and Database so its compatible with the classes from LNbits
> Refactor Compat and Database for LNbits comaptibility

- cashu/mint/ledger.py
- cashu/mint/migrations.py
> fix postgres views, closes #206

- cashu/lightning/lnbits.py
@callebtc tweak for #230 re-using a 'session' for the class rather than creating one for each request
> [Mint] LNBits backend refactor httpx

- cashu/core/p2pk.py
Fix for lnbits integration, needs relative imports.
> P2PK: relative import of secp

- cashu/wallet/wallet.py
Wallet: try except around mint info for mints that do not support it
> mint info: catch error

- .github/workflows/checks.yml
- .github/workflows/tests.yml
- Makefile
- poetry.lock
- pyproject.toml
- fix, make `test`
- use make command inside workflows
- use caching inside of workflows
- run formatting workflow every time not only on main branch
- update to poetry 1.5.1
> FEAT: improve on workflows and makefile

- .flake8
- .github/workflows/checks.yml
- .pre-commit-config.yaml
- Makefile
- cashu/core/base.py
- cashu/core/bolt11.py
- cashu/core/db.py
- cashu/core/migrations.py
- cashu/core/script.py
- cashu/mint/app.py
- cashu/mint/crud.py
- cashu/mint/ledger.py
- cashu/mint/migrations.py
- cashu/mint/router.py
- cashu/mint/startup.py
- cashu/wallet/api/router.py
- cashu/wallet/cli/cli.py
- cashu/wallet/cli/cli_helpers.py
- cashu/wallet/crud.py
- cashu/wallet/helpers.py
- cashu/wallet/migrations.py
- cashu/wallet/nostr.py
- cashu/wallet/wallet.py
- poetry.lock
- pyproject.toml
- tests/test_wallet.py
- precommit
- workflow
- Makefile
updated black
> [DEV] add ruff and remove isort and flake

- cashu/wallet/api/responses.py
- cashu/wallet/api/router.py
- cashu/wallet/cli/cli.py
- cashu/wallet/helpers.py
> Show all mints in cashu info

- .pre-commit-config.yaml
- cashu/wallet/crud.py
- cashu/wallet/wallet.py
- tests/test_wallet.py
accept new keyset id calculation, cache keysets, remove duplicate representations
> Wallet: Cache keysets

- cashu/mint/conditions.py
- cashu/wallet/p2pk.py
Also fix the same bug as in #398 for HTLCs
> sign outputs as bytes

- cashu/core/settings.py
- tests/test_crypto.py
- tests/test_wallet_restore.py
This pull request merges both h2c tests and adds tests for deterministic blinding factor generation.
> Merge both h2c tests and add tests for deterministic blinding factor generation

- cashu/mint/crud.py
- cashu/mint/ledger.py
- tests/test_mint_db.py
Mint: lookup internal quote settlement by request. Fixes https://github.com/cashubtc/nutshell/issues/477
> Refactor get_mint_quote_by_checking_id to get_mint_quote_by_request

- .github/workflows/pypi.yaml
This pull request adds a PyPi pipeline for uploading the package to PyPi.
> Add PyPi pipeline

- .env.example
Changed MINT_MAX_PEG_IN/OUT defaults to 10000
> Update .env.example, add MINT_MAX_BALANCE

- cashu/wallet/wallet.py
https://github.com/cashubtc/nutshell/issues/366
> Restore wallet now restores tokens for all mint keysets.

- cashu/core/base.py
- cashu/core/settings.py
- cashu/mint/ledger.py
- cashu/mint/migrations.py
- cashu/mint/router_deprecated.py
- cashu/wallet/wallet_deprecated.py
- tests/conftest.py
- tests/test_mint.py
- tests/test_mint_api.py
- tests/test_mint_api_deprecated.py
- tests/test_mint_init.py
- tests/test_wallet.py
- tests/test_wallet_restore.py
Persist deprecated keyset IDs to db.
> [Mint] Migrate duplicate keysets to db

- cashu/wallet/wallet.py
Refactored the request mint wallet method to generate the invoice  #from a returned MintQuoteResponse.
https://github.com/cashubtc/nutshell/issues/500
> Request Mint Refactor

- cashu/mint/startup.py
> startup: do not print postgres connection string, closes #523

- cashu/core/base.py
> Fix: default witness is None, closes #559

- cashu/core/base.py
- cashu/core/models.py
- cashu/mint/crud.py
- cashu/mint/ledger.py
- cashu/mint/migrations.py
- cashu/mint/router.py
- cashu/mint/router_deprecated.py
- cashu/wallet/v1_api.py
- cashu/wallet/wallet.py
- cashu/wallet/wallet_deprecated.py
- tests/test_mint_api.py
- tests/test_mint_operations.py
Change response model according to https://github.com/cashubtc/nuts/pull/136
> Fix: Nut 05 mint response model

- cashu/wallet/helpers.py
- tests/test_wallet_cli.py
> fix: cashu send --lock

- README.md
- cashu/mint/crud.py
- cashu/mint/db/read.py
- cashu/mint/protocols.py
- cashu/mint/verification.py
This pull request includes changes to refactor the database transactions. The changes involve updating the code related to getting spent proofs and promises, as well as verifying inputs and outputs. These changes aim to improve the efficiency and readability of the code.
> Refactor database transactions

- CONTRIBUTING.md
> `CONTRIBUTING.md`: Update contributing guidelines and environment setup

- cashu/core/models.py
- cashu/mint/router.py
- cashu/wallet/mint_info.py
- cashu/wallet/wallet_deprecated.py
Implements NUT-06 changes in the contact field of the info response: https://github.com/cashubtc/nuts/pull/117
> NUT-06: Mint contact info

- cashu/mint/features.py
- cashu/wallet/mint_info.py
> Fix NUT-17 settings entry for NUT-06

- cashu/wallet/transactions.py
- cashu/wallet/wallet.py
> Remove unused coinselection code

- cashu/wallet/wallet.py
Implements https://github.com/cashubtc/nuts/pull/151
> Wallet: Strip trailing slash from URL

- cashu/core/models.py
- cashu/mint/router.py
- cashu/wallet/cli/cli.py
- cashu/wallet/mint_info.py
implements https://github.com/cashubtc/nuts/issues/138
> implement nut-06 time

- poetry.lock
- pyproject.toml
- requirements.txt
first step of https://github.com/cashubtc/nutshell/issues/592
> bump bip32 and coincurve dependencies

- cashu/core/base.py
- cashu/core/helpers.py
- cashu/lightning/blink.py
- cashu/lightning/clnrest.py
- cashu/lightning/corelightningrest.py
- cashu/lightning/fake.py
- cashu/lightning/lnbits.py
- cashu/lightning/lnd_grpc/lnd_grpc.py
- cashu/lightning/lndrest.py
- cashu/mint/conditions.py
- cashu/mint/verification.py
- cashu/nostr/client/cbc.py
- cashu/nostr/filter.py
- cashu/tor/tor.py
- cashu/wallet/proofs.py
- cashu/wallet/v1_api.py
- use `{...}` instead of `set([...])`
- do not use `class Foo(object):`, just use `class Foo:`
- do not specify default flags (`"r"`) for `open()`
> chore: run pyupgrade

- cashu/wallet/v1_api.py
Accommodate changes from https://github.com/cashubtc/nuts/pull/136
> Wallet: handle PostMeltResponse_deprecated from v1 api

- cashu/wallet/wallet_deprecated.py
Implement error handling for JSON decoding issues to ensure that response status is raised appropriately when decoding fails.
> Wallet: deprecated api: Catch JSON decoding errors in response handling

- cashu/wallet/v1_api.py
Add compatibility handling for state checks with payloads from versions prior to 0.16.0, specifically addressing HTTP Error 422 responses. This change enhances the robustness of the state checking process.
> Ensure state check compatibility with versions < 0.16.0

- cashu/core/settings.py
- cashu/mint/ledger.py
- tests/test_mint_melt.py
Introduce a setting to disable melt on error by default
> Mint: Turn off locking by default

- cashu/mint/events/client.py
- cashu/mint/router.py
Implement error handling for websocket disconnections to improve stability and logging.
> Mint: Catch websocket disconnect errors

- README.md
- cashu/core/settings.py
- pyproject.toml
- setup.py
Update the version number across relevant files to reflect the new release 0.16.4.
> Bump version to 0.16.4

- .env.example
Introduce example settings for enabling response caching in Redis.
> Add NUT-19 example for caching responses

- .github/actions/prepare/action.yml
- .github/workflows/checks.yml
- .github/workflows/ci.yml
- .github/workflows/pypi.yaml
- .github/workflows/tests.yml
- .github/workflows/tests_redis_cache.yml
- Dockerfile
- README.md
there is a new poetry 2.0.0 in the wild and 1.8.5 is the latest of 1.x series
let's stick to that particular version consistently everywhere for now
> chore: use poetry the latest 1.8.x poetry consistently

- cashu/core/errors.py
- cashu/mint/verification.py
- tests/test_wallet.py
Follows [this](https://github.com/cashubtc/nuts/pull/223) spec change.
> Update Error Codes

- cashu/core/split.py
- cashu/lightning/blink.py
- cashu/mint/ledger.py
- tests/test_core.py
- tests/test_mint_lightning_blink.py
> Set correct blink min fee

- README.md
Add some Redis info (maybe not all this is needed?)
> Update README.md - Add Redis info?

- cashu/lightning/lnbits.py
Looks like lnbits changed its api with v1. Payment request is now in bolt11 field. This helped me to fix it.
> Fix getting the invoice from LNbits API

- tests/test_mint_init.py
Test for result of `get_melt_quote` with and without `rollback_unkown`
> Mint: add new init test to mint

- cashu/mint/ledger.py
- tests/test_mint_init.py
Our github pipeline gets stuck for postgres in regtest, I suspect it has something to do with the startup tasks but really not sure. Trying out a few things here to sample more data.
> Testing: check if pipeline gets stuck because of startup task

- README.md
- cashu/core/settings.py
- pyproject.toml
- setup.py
Update the version number across relevant files to reflect the new release 0.16.6.
> Bump version to 0.16.6

- README.md
- cashu/core/base.py
- cashu/core/models.py
- cashu/core/settings.py
- cashu/wallet/wallet.py
- pyproject.toml
- setup.py
Update the version number to 0.17.0 across various files and adjust backward compatibility comments accordingly.
> Bump version to 0.17.0
